'use strict';

const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.join(__dirname, '..');
const CSV_PATH = path.join(
  PROJECT_ROOT,
  'ship_tracks_2021-10-01_to_2021-10-01_191ships_207803positions.csv',
);
const OUT_PATH = path.join(PROJECT_ROOT, 'api', 'lib', 'data_10k.js');
const TARGET_COUNT = 10000;

function main() {
  if (!fs.existsSync(CSV_PATH)) {
    console.error('[extract10k] CSV not found:', CSV_PATH);
    process.exit(1);
  }

  console.log('[extract10k] reading CSV...');
  const raw = fs.readFileSync(CSV_PATH, 'utf-8');
  const lines = raw.trim().split(/\r?\n/);
  if (lines.length === 0) {
    console.error('[extract10k] CSV is empty');
    process.exit(1);
  }

  const headers = lines[0].split(',').map((h) => h.trim());
  const colIdx = {
    mmsi: headers.indexOf('MMSI'),
    lat: headers.indexOf('Latitude'),
    lng: headers.indexOf('Longitude'),
    sog: headers.indexOf('Speed Over Ground (SOG)'),
    cog: headers.indexOf('Course Over Ground (COG)'),
    heading: headers.indexOf('True Heading'),
    status: headers.indexOf('Navigational Status'),
    tsUnix: headers.indexOf('Timestamp (Unix)'),
  };

  const missing = Object.entries(colIdx).filter(([, idx]) => idx === -1);
  if (missing.length > 0) {
    console.error('[extract10k] missing columns:', missing.map(([k]) => k).join(', '));
    process.exit(1);
  }

  const records = [];
  for (let i = 1; i < lines.length && records.length < TARGET_COUNT; i++) {
    const line = lines[i];
    if (!line.trim()) continue;
    const cols = line.split(',');
    const ts = parseInt(cols[colIdx.tsUnix], 10);
    if (isNaN(ts)) continue;

    records.push({
      mmsi: parseInt(cols[colIdx.mmsi], 10) || 0,
      lat: parseFloat(cols[colIdx.lat]) || 0,
      lng: parseFloat(cols[colIdx.lng]) || 0,
      sog: cols[colIdx.sog] ? parseFloat(cols[colIdx.sog]) : null,
      cog: cols[colIdx.cog] ? parseFloat(cols[colIdx.cog]) : null,
      heading: cols[colIdx.heading] ? parseFloat(cols[colIdx.heading]) : null,
      status: cols[colIdx.status] ? parseInt(cols[colIdx.status], 10) : null,
      timestamp: ts,
    });
  }

  if (records.length === 0) {
    console.error('[extract10k] no valid records extracted');
    process.exit(1);
  }

  // 按时间排序，保持和 parseCsv 一致的行为
  records.sort((a, b) => a.timestamp - b.timestamp);

  const out = `// Auto-generated by scripts/extract10k.cjs\n// Source: ship_tracks_2021-10-01_to_2021-10-01_191ships_207803positions.csv\n// Record count: ${records.length}\n'use strict';\n\nmodule.exports = ${JSON.stringify(records)};\n`;

  fs.writeFileSync(OUT_PATH, out);
  console.log(`[extract10k] wrote ${records.length} records to ${OUT_PATH}`);
  console.log(`[extract10k] file size: ${(fs.statSync(OUT_PATH).size / 1024 / 1024).toFixed(2)} MB`);
}

main();
