'use strict';

const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

const PROJECT_ROOT = path.join(__dirname, '..');
const CSV_PATH = path.join(
  PROJECT_ROOT,
  'output',
  'merged_feichang_ships_2021-10-01_2021-11-30.csv.gz',
);
const OUT_PATH = path.join(PROJECT_ROOT, 'lib', 'api', 'data_10k.js');
const TARGET_COUNT = 10000;

function main() {
  if (!fs.existsSync(CSV_PATH)) {
    console.error('[extract10k] CSV not found:', CSV_PATH);
    process.exit(1);
  }

  console.log('[extract10k] reading CSV...');
  const raw = fs.readFileSync(CSV_PATH);
  const csvText = CSV_PATH.endsWith('.gz')
    ? zlib.gunzipSync(raw).toString('utf-8')
    : raw.toString('utf-8');
  const lines = csvText.trim().split(/\r?\n/);
  if (lines.length === 0) {
    console.error('[extract10k] CSV is empty');
    process.exit(1);
  }

  const headers = lines[0].split(',').map((h) => h.trim());
  const colIdx = {
    mmsi: headers.indexOf('mmsi'),
    lat: headers.indexOf('lat'),
    lng: headers.indexOf('lon'),
    sog: headers.indexOf('sog'),
    cog: headers.indexOf('cog'),
    heading: headers.indexOf('heading'),
    status: headers.indexOf('status'),
    tsMs: headers.indexOf('timestamp_ms'),
  };

  const missing = Object.entries(colIdx).filter(([, idx]) => idx === -1);
  if (missing.length > 0) {
    console.error('[extract10k] missing columns:', missing.map(([k]) => k).join(', '));
    process.exit(1);
  }

  const records = [];
  for (let i = 1; i < lines.length && records.length < TARGET_COUNT; i++) {
    const line = lines[i];
    if (!line.trim()) continue;
    const cols = line.split(',');
    const ts = parseInt(cols[colIdx.tsMs], 10);
    if (isNaN(ts)) continue;

    records.push({
      mmsi: parseInt(cols[colIdx.mmsi], 10) || 0,
      lat: parseFloat(cols[colIdx.lat]) || 0,
      lng: parseFloat(cols[colIdx.lng]) || 0,
      sog: cols[colIdx.sog] ? parseFloat(cols[colIdx.sog]) : null,
      cog: cols[colIdx.cog] ? parseFloat(cols[colIdx.cog]) : null,
      heading: cols[colIdx.heading] ? parseFloat(cols[colIdx.heading]) : null,
      status: cols[colIdx.status] ? parseInt(cols[colIdx.status], 10) : null,
      timestamp: Math.floor(ts / 1000),
    });
  }

  if (records.length === 0) {
    console.error('[extract10k] no valid records extracted');
    process.exit(1);
  }

  // 按时间排序，保持和 parseCsv 一致的行为
  records.sort((a, b) => a.timestamp - b.timestamp);

  const out = `// Auto-generated by scripts/extract10k.cjs\n// Source: output/merged_feichang_ships_2021-10-01_2021-11-30.csv.gz\n// Record count: ${records.length}\n'use strict';\n\nmodule.exports = ${JSON.stringify(records)};\n`;

  fs.writeFileSync(OUT_PATH, out);
  console.log(`[extract10k] wrote ${records.length} records to ${OUT_PATH}`);
  console.log(`[extract10k] file size: ${(fs.statSync(OUT_PATH).size / 1024 / 1024).toFixed(2)} MB`);
}

main();
